name: Git

on:
  schedule:
    - cron: 0 3 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "Dont care, and don't touch it!"
        required: true
        default: 'false'

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo Start
        sleep 3
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo Done
        
    - name: 安装必要软件包 (Installation of necessary packages)
      run: |
        echo Start
        echo $(uname -a) 
        sleep 5
        sudo apt update
        sudo apt install git zip unzip -y
        sudo apt-get install -y libfuse-dev neofetch 7zip
        sudo apt update
        sudo apt full-upgrade -y
        echo Done
        sleep 5
        mkdir giit
        cd giit
        curl https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/lede.sh | bash
        sleep 3
        curl https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/istoreos.sh | bash
        sleep 3
        curl https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/openwrt.sh | bash
        sleep 3
        curl https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/smartdns.sh | bash
        echo "完成"

    - name: 检查空间使用情况 (Check space usage)
      if: (!cancelled())
      run: df -hT

    - name:  上传目录 (Upload bin directory)
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: giit

    - name: 生成发布标签 (Generate publish tags)
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "自动生成 (Automatic compilation)" >> release.txt
        echo "- 本仓库禁止克隆到[GitCode](https://gitcode.com)" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件以发布 (Upload firmware for release)
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: giit/*.zip
     
    - name: 删除工作流运行 (Delete workflow run)
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
